version: "3.7" # 目前使用的版本，可以參考官網：
services: # services 關鍵字後面列出 web, redis 兩項專案中的服務
  Website:
    restart: always
    build: 
      context: ./
      dockerfile: Dockerfile # Build 在同一資料夾的 Dockerfile（描述 Image 要組成的 yaml 檔案）成 container
    image: innodiskorg/ijarvis-website:v100
    container_name: ijarvis-website
    environment:
      - NGINX_PORT=3002
      - BACKEND_PORT=9527
      - BACKEND_SERVER=10.204.16.53
    command: >
      /bin/sh -c
      "envsubst '
      $${NGINX_PORT}
      $${BACKEND_PORT}
      $${BACKEND_SERVER}
      '< /etc/nginx/nginx.conf.template
      > /etc/nginx/nginx.conf
      && nginx -g 'daemon off;'"
    network_mode: host

